#! /bin/sh

satpg=../opt/programs/satpg/src/atpg_tclsh/atpg_tclsh

blifdir="~/share/data/MCNC.blifdata"
iscas89dir="~/share/data/ISCAS.s/COMBI"
itcdir="~/data/public/itc99"

bliflist=`cat bliflist`
iscas89list=`cat iscas89list`
itclist=`cat itclist`

modelist="\
single single_po single_po_skip \
dual dual_po dual_po_skip \
ffr ffr_po ffr_po_skip \
mffc mffc_po_skip"

for name in $bliflist; do
  path=$blifdir/$name
  echo ""
  echo $path
  for mode in $modelist; do
    $satpg $mode $path
  done
done

for name in $iscas89list; do
  path=$iscas89dir/$name
  echo ""
  echo $path
  for mode in $modelist; do
    $satpg $mode $path
  done
done

for name in $itclist; do
  path=$itcdir/$name
  echo ""
  echo $path
  for mode in $modelist; do
    $satpg $mode $path
  done
done
