#! /bin/sh

# Copyright (C) 2005-2011, 2014 Yusuke Matsunaga
# All rights reserved

# 概要
#
# モジュールの Makefile を更新するスクリプト
#
# 使用方法
#
# ./update <module-name> ...

case $# in
    0)
	echo "Usage: $0 <module-name> ..."
	exit 1
	;;
esac

while [ $# -gt 0 ]
do
    if [ ! -d $1 ]; then
	echo "$1: no such directory. skipping"
    else
	(cd $1; make Makefile)
    fi
    shift
done
