#! /bin/sh

# Copyright (C) 2005-2011 Yusuke Matsunaga
# All rights reserved

# [概要]
#
# モジュールの Makefile を更新するスクリプト
#
# [使用方法]
#
# ./update <module-name> ...

case $# in
    1)
	echo "Usage: $0 <module-name> ..."
	exit 255
	;;
esac

for dir in opt debug prof
do
  (cd $dir/$1; make Makefile)
done
